In [31]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [4]:
df=pd.read_csv('/home/mariam/Projects/research-paper-recommender/data/arxiv_data_210930-054931.csv')

In [5]:
df.head()

,terms,titles,abstracts
0,['cs.LG'],Multi-Level Attention Pooling for Graph Neural...,Graph neural networks (GNNs) have been widely ...
1,"['cs.LG', 'cs.AI']",Decision Forests vs. Deep Networks: Conceptual...,Deep networks and decision forests (such as ra...
2,"['cs.LG', 'cs.CR', 'stat.ML']",Power up! Robust Graph Convolutional Network v...,Graph convolutional networks (GCNs) are powerf...
3,"['cs.LG', 'cs.CR']",Releasing Graph Neural Networks with Different...,With the increasing popularity of Graph Neural...
4,['cs.LG'],Recurrence-Aware Long-Term Cognitive Network f...,Machine learning solutions for pattern classif...

In [7]:
df.shape

(56181, 3)

In [8]:
df.columns

Index(['terms', 'titles', 'abstracts'], dtype='str')

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56181 entries, 0 to 56180
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   terms      56181 non-null  str
 1   titles     56181 non-null  str
 2   abstracts  56181 non-null  str
dtypes: str(3)
memory usage: 1.3 MB

In [10]:
df.isnull().sum()

terms        0
titles       0
abstracts    0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(15054)

In [12]:
df.nunique()

terms         3402
titles       41105
abstracts    41115
dtype: int64

In [13]:
df[df.duplicated(keep=False)].head(10)

,terms,titles,abstracts
0,['cs.LG'],Multi-Level Attention Pooling for Graph Neural...,Graph neural networks (GNNs) have been widely ...
1,"['cs.LG', 'cs.AI']",Decision Forests vs. Deep Networks: Conceptual...,Deep networks and decision forests (such as ra...
2,"['cs.LG', 'cs.CR', 'stat.ML']",Power up! Robust Graph Convolutional Network v...,Graph convolutional networks (GCNs) are powerf...
3,"['cs.LG', 'cs.CR']",Releasing Graph Neural Networks with Different...,With the increasing popularity of Graph Neural...
4,['cs.LG'],Recurrence-Aware Long-Term Cognitive Network f...,Machine learning solutions for pattern classif...
5,"['cs.LG', 'stat.ML']",Lifelong Graph Learning,Graph neural networks (GNNs) are powerful mode...
6,['cs.LG'],Bayesian graph convolutional neural networks v...,"Deep learning models, such as convolutional ne..."
7,"['cs.LG', 'stat.ML']",Understanding and Resolving Performance Degrad...,A Graph Convolutional Network (GCN) stacks sev...
8,['cs.LG'],Edge-augmented Graph Transformers: Global Self...,Transformer neural networks have achieved stat...
9,"['cs.LG', 'cs.AI']",Variational Graph Normalized Auto-Encoders,Link prediction is one of the key problems for...

In [14]:
df['titles'].value_counts().head(10)

titles
Learning Local Neighboring Structure for Robust 3D Shape Representation                              7
Point Transformer                                                                                    7
Transformers in Vision: A Survey                                                                     7
Deep Reinforcement Learning: An Overview                                                             7
Learnable Hypergraph Laplacian for Hypergraph Learning                                               6
Graph Representation Learning via Graphical Mutual Information Maximization                          6
A Survey on Machine Learning Techniques for Auto Labeling of Video, Audio, and Text Data             6
Applications of Deep Neural Networks                                                                 6
Ensemble Augmentation for Deep Neural Networks Using 1-D Time Series Vibration Data                  6
Generic Attention-model Explainability for Interpreting Bi-Modal and Encoder-Decoder Transformers    6
Name: count, dtype: int64

In [16]:
title = df['titles'].value_counts().index[0]
title

'Learning Local Neighboring Structure for Robust 3D Shape Representation'

In [17]:
df[df['titles'] == title][['terms', 'titles', 'abstracts']]

,terms,titles,abstracts
162,"['cs.CV', 'cs.LG', 'eess.IV']",Learning Local Neighboring Structure for Robus...,Mesh is a powerful data structure for 3D shape...
990,"['cs.CV', 'cs.LG', 'eess.IV']",Learning Local Neighboring Structure for Robus...,Mesh is a powerful data structure for 3D shape...
15261,"['cs.CV', 'cs.LG', 'eess.IV']",Learning Local Neighboring Structure for Robus...,Mesh is a powerful data structure for 3D shape...
25685,"['cs.CV', 'cs.LG', 'eess.IV']",Learning Local Neighboring Structure for Robus...,Mesh is a powerful data structure for 3D shape...
35547,"['cs.CV', 'cs.LG', 'eess.IV']",Learning Local Neighboring Structure for Robus...,Mesh is a powerful data structure for 3D shape...
48434,"['cs.CV', 'cs.LG', 'eess.IV']",Learning Local Neighboring Structure for Robus...,Mesh is a powerful data structure for 3D shape...
53908,"['cs.CV', 'cs.LG', 'eess.IV']",Learning Local Neighboring Structure for Robus...,Mesh is a powerful data structure for 3D shape...

In [18]:
df[df['titles'] == title]['abstracts'].nunique()

1

We found that some papers appear multiple times in the dataset. For example, the paper "Learning Local Neighboring Structure for Robust 3D Shape Representation" appeared seven times with exactly the same terms, title, and abstract.

In [19]:
df = df.drop_duplicates()

In [20]:
df.duplicated().sum()

np.int64(0)

In [21]:
df.shape

(41127, 3)

In [23]:
df['terms'].nunique()

3402

In [24]:
df[['titles', 'abstracts']].describe()

,titles,abstracts
count,41127,41127
unique,41105,41115
top,Learnable Hypergraph Laplacian for Hypergraph ...,HyperGraph Convolutional Neural Networks (HGCN...
freq,2,2

In [25]:
df['title length']=df['titles'].str.split().str.len()
df['abstract length']=df['abstracts'].str.split().str.len()

In [26]:
df[['title length', 'abstract length']].describe()

       title length  abstract length
count  41127.000000     41127.000000
mean       8.901476       171.456975
std        3.040075        45.950679
min        1.000000         5.000000
25%        7.000000       140.000000
50%        9.000000       169.000000
75%       11.000000       201.000000
max       30.000000       498.000000

In [27]:
df[['titles', 'abstracts']].sample(5, random_state=42)

,titles,abstracts
28691,GAN-based Priors for Quantifying Uncertainty,Bayesian inference is used extensively to quan...
29603,Bidirectional Conditional Generative Adversari...,Conditional Generative Adversarial Networks (c...
11048,Meta Reinforcement Learning with Distribution ...,"In this paper, we propose a novel meta-learnin..."
19930,xYOLO: A Model For Real-Time Object Detection ...,With the emergence of onboard vision processin...
17046,ContraGAN: Contrastive Learning for Conditiona...,Conditional image generation is the task of ge...

In [28]:
df['text'] = df['titles'] + ' ' + df['abstracts']

In [29]:
df[['titles', 'abstracts', 'text']].head(2)

,titles,abstracts,text
0,Multi-Level Attention Pooling for Graph Neural...,Graph neural networks (GNNs) have been widely ...,Multi-Level Attention Pooling for Graph Neural...
1,Decision Forests vs. Deep Networks: Conceptual...,Deep networks and decision forests (such as ra...,Decision Forests vs. Deep Networks: Conceptual...

In [32]:
df.to_csv("../data/arxiv_cleaned.csv", index=False)